#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, env, configprops

spring:
  application:
    name: note-taking-service

  data:
    web:
      pageable:
        max-page-size: 100 
        default-page-size: 20
  
  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb://localhost:27017/bluestaq_itdepartment_user_notes_db}    
    auto-index-creation: true